# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-04 20:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.TextField(blank=True, null=True, unique=True)),
                ('name', models.TextField(blank=True, null=True)),
                ('author', models.TextField(blank=True, null=True)),
                ('press', models.TextField(blank=True, null=True)),
                ('date', models.TextField(blank=True, null=True)),
                ('page', models.TextField(blank=True, null=True)),
                ('price', models.TextField(blank=True, null=True)),
                ('score', models.TextField(blank=True, null=True)),
                ('isbn', models.TextField(blank=True, db_column='ISBN', null=True)),
                ('author_profile', models.TextField(blank=True, null=True)),
                ('content_description', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'books',
                'managed': False,
            },
        ),
    ]
