# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-13 17:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ActivitiesRecord',
            fields=[
                ('activity_id', models.CharField(max_length=200, primary_key=True, serialize=False, unique=True)),
                ('access_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('game_name', models.CharField(max_length=200, primary_key=True, serialize=False, unique=True)),
                ('cost_per_time', models.IntegerField()),
                ('game_description', models.CharField(max_length=400)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('transaction_id', models.CharField(max_length=200, primary_key=True, serialize=False, unique=True)),
                ('transaction_amount', models.IntegerField()),
                ('transaction_date', models.DateField()),
                ('transaction_type', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.CharField(max_length=200, primary_key=True, serialize=False, unique=True)),
                ('user_name', models.CharField(max_length=100)),
                ('user_password', models.CharField(max_length=200)),
                ('user_level', models.IntegerField()),
                ('user_balance', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='transaction',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='User_Management.User'),
        ),
        migrations.AddField(
            model_name='activitiesrecord',
            name='game_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='User_Management.Game'),
        ),
        migrations.AddField(
            model_name='activitiesrecord',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='User_Management.User'),
        ),
    ]
