# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-28 17:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User_Management', '0002_activitiesrecord_activity_cost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitiesrecord',
            name='access_date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='activitiesrecord',
            name='activity_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transaction_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
