# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-28 17:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User_Management', '0003_auto_20170728_1742'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='transaction_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
